import { AlertTriangle, ChevronLeft, ChevronRight, Clock3, Search, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatBytes, mutate, shortSha } from '../api';
import { useToast } from '../components/Toast';
import { Card, Empty, Loading, Modal, PageHeader, StatusBadge } from '../components/UI';
import { useApi } from '../hooks';
import type { Repository, Run } from '../types';

type Result={items:Run[];page:number;pageSize:number;total:number;pages:number};
export default function HistoryPage(){const{t,i18n}=useTranslation();const toast=useToast();const[filters,setFilters]=useState({search:'',repositoryId:'',branch:'',status:'',from:'',to:''});const[page,setPage]=useState(1);const[clear,setClear]=useState(false);const[detail,setDetail]=useState<Run>();
  const params=useMemo(()=>{const p=new URLSearchParams({page:String(page),pageSize:'25'});Object.entries(filters).forEach(([k,v])=>{if(v)p.set(k,k==='from'?new Date(`${v}T00:00:00`).toISOString():k==='to'?new Date(`${v}T23:59:59`).toISOString():v)});return p.toString()},[filters,page]);const{data,loading,refresh}=useApi<Result>(`/history?${params}`,10000);const{data:repos}=useApi<{items:Repository[]}>('/repositories');
  const date=(v?:string)=>v?new Intl.DateTimeFormat(i18n.language,{dateStyle:'medium',timeStyle:'medium'}).format(new Date(v)):'—';const set=(key:string,value:string)=>{setFilters(x=>({...x,[key]:value}));setPage(1)};
  const clearHistory=async()=>{try{await mutate('/history','DELETE');toast(t('historyCleared'));setClear(false);void refresh()}catch{toast(t('unexpectedError'),'error')}};
  return <><PageHeader title={t('executionHistory')} description={`${data?.total||0} ${t('history').toLowerCase()}`} actions={<button className="button danger-outline" onClick={()=>setClear(true)}><Trash2/>{t('clearHistory')}</button>}/><Card className="filters"><div className="filter-grid"><label className="search-field"><Search/><input value={filters.search} onChange={e=>set('search',e.target.value)} placeholder={t('search')} aria-label={t('search')}/></label><label><span>{t('repository')}</span><select value={filters.repositoryId} onChange={e=>set('repositoryId',e.target.value)}><option value="">{t('allRepositories')}</option>{repos?.items.map(r=><option key={r.id} value={r.id}>{r.owner}/{r.name}</option>)}</select></label><label><span>{t('branch')}</span><input value={filters.branch} onChange={e=>set('branch',e.target.value)}/></label><label><span>{t('status')}</span><select value={filters.status} onChange={e=>set('status',e.target.value)}><option value="">{t('allStatuses')}</option>{['queued','running','success','failed'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label><label><span>{t('from')}</span><input type="date" value={filters.from} onChange={e=>set('from',e.target.value)}/></label><label><span>{t('to')}</span><input type="date" value={filters.to} onChange={e=>set('to',e.target.value)}/></label></div></Card>
    <Card>{loading?<Loading/>:!data?.items.length?<Empty icon={<Clock3/>} title={t('noRuns')}/>:<div className="responsive-table history-table"><table><thead><tr><th>{t('repository')}</th><th>{t('branch')}</th><th>{t('started')}</th><th>{t('duration')}</th><th>{t('status')}</th><th>{t('commit')}</th><th>{t('size')}</th><th>{t('origin')}</th></tr></thead><tbody>{data.items.map(run=><tr key={run.id} className={run.error?'clickable':''} tabIndex={run.error?0:undefined} role={run.error?'button':undefined} onKeyDown={event=>{if(run.error&&(event.key==='Enter'||event.key===' ')){event.preventDefault();setDetail(run)}}} onClick={()=>run.error&&setDetail(run)}><td data-label={t('repository')}><b>{run.owner}/{run.repository}</b></td><td data-label={t('branch')}>{run.branch}</td><td data-label={t('started')}>{date(run.started_at||run.created_at)}</td><td data-label={t('duration')}>{run.started_at&&run.completed_at?`${((new Date(run.completed_at).getTime()-new Date(run.started_at).getTime())/1000).toFixed(1)}s`:'—'}</td><td data-label={t('status')}><StatusBadge status={run.status}/></td><td data-label={t('commit')}><code>{shortSha(run.commit_sha)}</code></td><td data-label={t('size')}>{formatBytes(run.size_bytes)}</td><td data-label={t('origin')}>{t(run.origin)}</td></tr>)}</tbody></table></div>}{data&&data.pages>1&&<div className="pagination"><button className="button ghost small" disabled={page<=1} onClick={()=>setPage(x=>x-1)}><ChevronLeft/>{t('previous')}</button><span>{t('page')} {page} {t('of')} {data.pages}</span><button className="button ghost small" disabled={page>=data.pages} onClick={()=>setPage(x=>x+1)}>{t('next')}<ChevronRight/></button></div>}</Card>
    <Modal open={clear} onClose={()=>setClear(false)} title={t('clearHistoryTitle')} footer={<><button className="button ghost" onClick={()=>setClear(false)}>{t('cancel')}</button><button className="button danger" onClick={clearHistory}>{t('clearHistory')}</button></>}><div className="warning-box"><AlertTriangle/><p>{t('clearHistoryWarning')}</p></div></Modal>
    <Modal open={!!detail} onClose={()=>setDetail(undefined)} title={t('errorDetails')}><div className="error-detail"><StatusBadge status={detail?.status}/><p>{detail?.owner}/{detail?.repository} · {detail?.branch}</p><pre>{detail?.error}</pre>{detail?.destination&&<code>{detail.destination}</code>}</div></Modal>
  </>}
