import { AlertTriangle, Database, FolderSync, HardDrive, RefreshCw } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { formatBytes, mutate } from '../api';
import { useToast } from '../components/Toast';
import { Card, Loading, PageHeader } from '../components/UI';
import { useApi } from '../hooks';

type StorageData={root?:string;hostPath?:string;capacity:number;used:number;free:number;backupsUsed:number;lowSpace:boolean;minimumFree:number;byRepository:Array<{id:number;owner:string;name:string;sizeBytes:number;backups:number}>;byBranch:Array<{id:number;owner:string;repository:string;branch:string;sizeBytes:number;backups:number}>};
export default function Storage(){const{t}=useTranslation();const toast=useToast();const{data,loading,refresh}=useApi<StorageData>('/storage',15000);const action=async(kind:'reconcile'|'retention')=>{try{await mutate(`/storage/${kind}`,'POST');toast(t(kind==='reconcile'?'reconciled':'retentionComplete'));await refresh()}catch{toast(t('unexpectedError'),'error')}};
  if(loading)return <Loading/>;const percent=data?.capacity?Math.min(100,data.used/data.capacity*100):0;
  return <><PageHeader title={t('storageManagement')} description={t('configuredRoot')} actions={<><button className="button secondary" onClick={()=>action('reconcile')}><FolderSync/>{t('reconcile')}</button><button className="button secondary" onClick={()=>action('retention')}><RefreshCw/>{t('runRetention')}</button></>}/>{data?.lowSpace&&<div className="alert-banner"><AlertTriangle/><div><b>{t('lowSpace')}</b><span>{t('lowSpaceHelp')}</span></div></div>}
    <Card className="storage-hero"><div className="storage-icon"><HardDrive/></div><div className="storage-main"><span>{t('configuredRoot')}</span>{data?.hostPath&&<code>{data.hostPath}</code>}{data?.root&&<small>{t('containerPath')}: {data.root}</small>}<div className="capacity-bar"><i style={{width:`${percent}%`}}/></div><div className="capacity-labels"><b>{formatBytes(data?.used)} / {formatBytes(data?.capacity)}</b><span>{percent.toFixed(1)}%</span></div></div></Card>
    <div className="metric-grid storage-metrics"><Card className="metric"><div className="metric-icon"><HardDrive/></div><div><span>{t('filesystemCapacity')}</span><strong>{formatBytes(data?.capacity)}</strong></div></Card><Card className="metric"><div className="metric-icon"><Database/></div><div><span>{t('backupSpace')}</span><strong>{formatBytes(data?.backupsUsed)}</strong></div></Card><Card className="metric"><div className="metric-icon"><HardDrive/></div><div><span>{t('spaceFree')}</span><strong>{formatBytes(data?.free)}</strong></div></Card></div>
    <div className="two-column"><Card title={t('storageByRepository')}><div className="usage-list">{data?.byRepository.map(row=><div key={row.id}><span><b>{row.owner}/{row.name}</b><small>{row.backups} {t('backups').toLowerCase()}</small></span><strong>{formatBytes(row.sizeBytes)}</strong><i><em style={{width:`${data.backupsUsed?row.sizeBytes/data.backupsUsed*100:0}%`}}/></i></div>)}</div></Card><Card title={t('storageByBranch')}><div className="usage-list">{data?.byBranch.slice(0,20).map(row=><div key={row.id}><span><b>{row.repository} · {row.branch}</b><small>{row.backups} {t('backups').toLowerCase()}</small></span><strong>{formatBytes(row.sizeBytes)}</strong><i><em style={{width:`${data.backupsUsed?row.sizeBytes/data.backupsUsed*100:0}%`}}/></i></div>)}</div></Card></div><p className="help-text">{t('reconcileHelp')}</p>
  </>}
